# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViroSample' do
  pod 'AppCenter/Analytics', '~> 1.12.0'
  pod 'AppCenterReactNativeShared', '~> 1.11.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ViroSample

  

  platform :ios, '9.0'
  target 'ViroSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ViroSample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ViroSample-tvOS

  target 'ViroSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
